### ISSUE TITLE
Add distance measurement tool

### ISSUE THREAD

**Issue by Manonbd** [WelcometoMyGarden/welcometomygarden#96] opened 2021-01-12 10:46 UTC
Request from traveller : _"With it, it would be possible to have rough estimate as to how far away a given garden is to your hiking trail. For hiking this is very interesting feature, given that a 2 km drift off of your route, roughly sets you back an hour in total, from and back to your hiking trail."_

**Comment by MichielLeyman** [comment] 2021-04-30 20:05
Thanks! This is a duplicate of #82

**Closed by MichielLeyman** 2021-04-30 20:05 UTC
Labels: duplicate
