### ISSUE TITLE
Spacing under nav bar

### ISSUE THREAD

**Issue by wietsevr** [WelcometoMyGarden/welcometomygarden#37] opened 2020-06-25 21:16 UTC
<img width="1263" alt="Screen Shot 2020-06-25 at 23 10 56" src="https://user-images.githubusercontent.com/11728606/85796167-c1c2a800-b739-11ea-885f-ea38a787de2a.png">
Content is hidden under the navbar. Spacing to be added under nav bar?

**Comment by MichielLeyman** [comment] 2020-06-26 12:13
Hi Wietse! Strange resolution - what device is?

**Comment by wietsevr** [comment] 2020-06-27 15:19
This is on desktop (Macbook Pro 15" - accessed via Chrome).

**Comment by MichielLeyman** [comment] 2020-07-12 16:17
I can't seem to reproduce this on any common resolution, is your console open?

I can't give spacing if there isn't any left. If this is a problem, we could make the card scrollable and decrease the size of the footer. I have yet to find a screen resolution like this one though

**Comment by MichielLeyman** [comment] 2020-08-28 13:39
Cannot reproduce, but fixing #40 will likely fix this. Closing until we get another report for this issue.

**Closed by MichielLeyman** 2020-08-28 13:39 UTC
